project:
  type: website

website:
  title: "Python pour les nuls"
  back-to-top-navigation: true
  navbar:
    background: light
    foreground: black
    left:
      - text: Accueil
        file: Python.qmd
      - text: Les fondamentaux
        file: Fondamentaux.qmd
      - text: Gestion des exceptions
        file: Exceptions.qmd
      - text: S'entrainer
        file: Exercices.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/mareva-perez-b26a4a258/
      - icon: github
        menu:
          - text: Code source
            href: https://github.com/marevz/Learn-Together-main


  search: 
    location: navbar
    type: textbox

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true


