project:
  type: website

website:
  navbar:
    tools: 
      - search: true
        button_text: Search
    background: light
  
    left: 
      - text: Introduction
        file: Python.qmd
      - text: Les fondamentaux
        file: Fondamentaux.qmd
      - text: Gestion des exceptions
        file: Exceptions.qmd
      - text: S'entrainer
        file: Exercices.qmd



format:
  html:
    theme: zephyr
    css: styles.css
    toc: true




